// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CharacterCollectionContext))]
    [Migration("20220615184350_2nd Migration")]
    partial class _2ndMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationCore.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Iron Man",
                            Power = 989
                        },
                        new
                        {
                            Id = 2,
                            Name = "Captain America",
                            Power = 991
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thor",
                            Power = 999
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hulk",
                            Power = 998
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Villain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Weakness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Villian");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thanos",
                            Power = 999
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ebony Maw",
                            Power = 990
                        },
                        new
                        {
                            Id = 3,
                            Name = "Loki",
                            Power = 850
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ultron",
                            Power = 999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
